# Generated by Django 4.2.25 on 2026-01-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon"),
                            ("shield", "Shield"),
                            ("armour", "Armour"),
                            ("relic", "Relic"),
                            ("consumable", "Consumable"),
                        ],
                        default="weapon",
                        max_length=20,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("mythic", "Mythic"),
                            ("relic", "Relic"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                (
                    "price_pence",
                    models.PositiveIntegerField(
                        help_text="Price in pence (e.g. 1299 = £12.99)"
                    ),
                ),
                ("stock_qty", models.PositiveIntegerField(default=0)),
                ("short_description", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
