# Generated by Django 4.2.25 on 2026-01-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_asset_productimage_productimage_uniq_product_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("weapon", "Weapon"),
                    ("shield", "Shield"),
                    ("armour", "Armour"),
                    ("relic", "Relic"),
                    ("consumable", "Consumable"),
                    ("spell", "Spell"),
                ],
                default="weapon",
                max_length=20,
            ),
        ),
    ]
