# Generated by Django 4.2.25 on 2026-01-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_sku"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("armour_set", "Armour Set"),
                            ("weapon_family", "Weapon Family"),
                            ("spell_school", "Spell School"),
                        ],
                        default="armour_set",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon"),
                            ("shield", "Shield"),
                            ("armour", "Armour"),
                            ("relic", "Relic"),
                            ("consumable", "Consumable"),
                            ("spell", "Spell"),
                        ],
                        default="armour",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "primary_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_for_groups",
                        to="catalog.product",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="catalog.product"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
