# Generated by Django 4.2.25 on 2026-01-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_subtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="subtype",
            field=models.CharField(
                choices=[
                    ("cloth", "Cloth"),
                    ("leather", "Leather"),
                    ("plate", "Plate"),
                    ("other", "Other"),
                    ("sword", "Sword"),
                    ("axe", "Axe"),
                    ("polearm", "Polearm"),
                    ("staff", "Staff"),
                    ("bow", "Bow"),
                    ("dagger", "Dagger"),
                    ("hammer", "Hammer"),
                    ("whip", "Whip"),
                    ("fist", "Fist"),
                    ("sorcery", "Sorcery"),
                    ("incantation", "Incantation"),
                    ("ashes_of_war", "Ashes of War"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
