# Generated by Django 4.2.25 on 2026-01-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_session_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
