# Generated by Django 4.2.25 on 2026-03-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_stripe_session_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
