# Generated by Django 4.2.25 on 2026-03-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_paid_email_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
