# Generated by Django 4.2.25 on 2026-03-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_fulfilled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("placed", "Placed"),
                    ("paid", "Paid"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
